import React from "react";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <p
          style={{
            position: "absolute",
            top: "0",
            left: "0",
            paddingBlock: 5,
            zIndex: "1000",
            textAlign: "center",
            width: "100vw",
          }}
        >
          {" "}
          Same Component replicated on two pages , same classes but two diffrent
          configs{" "}
        </p>
        {children}
      </body>
    </html>
  );
}
